language: perl

sudo: false

install:
  - cpanm -n Mojolicious
  - cpanm -n Template
script: HARNESS_IS_VERBOSE=1 prove -v -Ilib t
perl:
  - "5.21"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
